# Generated by Django 3.2.8 on 2021-11-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('birthDate', models.TextField(max_length=50)),
                ('username', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
            ],
        ),
    ]
