# Generated by Django 3.2.8 on 2021-11-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrumboard', '0002_user2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=10000)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.CharField(max_length=500)),
            ],
        ),
    ]
